Added bzl_libraries for stardoc support
bazelbuild/rules_foreign_cc pull request #453
Opened 2021-01-09 19:39 UTC by UebelAndre

There's now a top level [bzl_library](https://github.com/bazelbuild/bazel-skylib#bzl_library) `@rules_foreign_cc//:bzl_srcs` that contain the `.bzl` sources for the build rules defined in this repo.

Stardoc support was also added to ensure the `bzl_library` structure is correct and usable outside of the repo. In addition to this, new documentation can be generated by running `bazel run //docs:generate_docs` from the root of `rules_foreign_cc` to output `@rules_foreign_cc//docs:README.md`.

This PR also fixes an issue in CI where `gmp` was no longer accessible via `.tar.gz`. The repository definition now uses a `tar.bz2` archive.

2021-01-19 02:23 UTC, UebelAndre commented
@oquenchil Hey, are you around to take a look at this? 🙏

2021-01-19 23:24 UTC, whs-dot-hk commented
Hi, @UebelAndre I think this is unrelated to building (cmake, make, configure make, etc)

2021-01-19 23:28 UTC, UebelAndre commented
This exposes the `.bzl` files as a `bzl_library` so that other rules/macros that depend on them can continue to have documentation generated via stardoc.

I ran into this because we replaced a custom rule with `configure_make` and broke our ability to generate documentation. If this PR gets merged, we no longer have to make the decision between generated documentation and a more canonical way to integrate older code into Bazel.

2021-01-20 00:44 UTC, UebelAndre commented
@whs-dot-hk If you're interested, https://github.com/UebelAndre/rules_foreign_cc/tree/stardoc/examples/docs is the direct result of the changes in this PR (not including fixing CI) 😄 

I'd greatly appreciate having this merged. Documentation is really important to my team and one of our favorite parts of Bazel 😄

2021-01-20 16:01 UTC, UebelAndre commented
I have another branch with all the docs plugged in. I find this incredibly helpful: [@rules_foreign_cc//examples/docs/...](https://github.com/UebelAndre/rules_foreign_cc/tree/a76e06d7603966233d1e3ef5696802e9f37c38be/examples/docs)

2021-01-20 17:28 UTC, UebelAndre commented
@irengrig Hey, are you available to take a look at this PR? 🙏 😅

2021-01-22 14:04 UTC, jsharpe requested changes
Looks good; its useful to have the functions documented properly without having to read through the code.

Just a couple of nits with formatting and an unrelated change to the top level WORKSPACE to remove and then this will be good to go.

It's probably worth adding a link to the docs on the top level README file too?

2021-01-22 14:04 UTC, jsharpe commented on workspace_definitions.bzl
> +    """
nit: remove the trailing whitespace

2021-01-22 14:21 UTC, UebelAndre commented on WORKSPACE
> -
Can do, it's been removed from this PR

2021-01-22 14:24 UTC, UebelAndre commented on WORKSPACE
> -
oops, forgot to push this change. Now it's been dropped.

2021-01-22 14:25 UTC, jsharpe approved these changes
LGTM

2021-01-22 14:25 UTC, merged