Ensure symlink_contents_to_dir traverses symlinks on OSX
bazelbuild/rules_foreign_cc pull request #512
Opened 2021-02-17 03:39 UTC by jlaxson

If the `source` arg to symlink_contents_to_dir is itself a symlink, the `find` call wouldn't traverse it.  I believe I encountered this when trying to chain `configure_make` rules where the first rule generated a shared library. 

Another solution would be to pass `-L` to find, but that would make it traverse all symlinks, not just the root, and this seemed closer to original intent.

2021-02-23 16:28 UTC, UebelAndre requested changes
One question so far and could I get you to somehow add a test for this functionality so it doesn't regress in the future? 🙏

2021-02-23 16:28 UTC, UebelAndre commented on tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl
> +  local children=($(find "$1/" -maxdepth 1 -mindepth 1))
Is this not an issue on Linux as well?

2021-05-06 00:54 UTC, UebelAndre commented
I think this might have been solved for in https://github.com/bazelbuild/rules_foreign_cc/pull/603. @jlaxson could you try updating and see if your problem is resolved?

2021-07-19 18:53 UTC, jsharpe commented
This change was addressed in #603

2021-07-19 18:53 UTC, closed without merging