Add a configure_nmake rule
bazelbuild/rules_foreign_cc pull request #735
Opened 2021-07-21 13:57 UTC by jheaff1

Note that the msvc constraint was removed from the
exec_compatible_with attribute of preinstalled_nmake_toolchain as
the condition is not actually met even when building with msvc. See
bazelbuild/bazel#7730.

This will be tested in PR #729

2021-07-21 14:55 UTC, UebelAndre requested changes
One thing that sucks about having a separate target is that consumers of these rules now need to be aware of the difference when defining library paths and such:
https://github.com/bazelbuild/rules_foreign_cc/blob/c7330faee503cc1b4e7280769480b540fe91cc86/examples/third_party/curl/BUILD.curl.bazel#L12

By having two different rules, there will likely be two different targets and users now have to account for this. Or, if we're to go with this solution, how can we avoid users having to select on each time they have a cross-platform target?

2021-07-21 15:10 UTC, jheaff1 commented
> One thing that sucks about having a separate target is that consumers of these rules now need to be aware of the difference when defining library paths and such:
> https://github.com/bazelbuild/rules_foreign_cc/blob/c7330faee503cc1b4e7280769480b540fe91cc86/examples/third_party/curl/BUILD.curl.bazel#L12
> 
> By having two different rules, there will likely be two different targets and users now have to account for this. Or, if we're to go with this solution, how can we avoid users having to select on each time they have a cross-platform target?

I came across this exact issue in PR #729. Thankfully the solution was simply setting the `lib_name` attribute of the two `openssl` targets to be `openssl`. Dependants such as curl then need only refer to the `openssl` directory

2021-07-21 15:48 UTC, UebelAndre commented
https://github.com/bazelbuild/rules_foreign_cc/pull/734#discussion_r674106039

2021-07-28 14:47 UTC, closed without merging

2021-07-28 14:48 UTC, jheaff1 commented
Superseded by #734