Build log4cxx
bazelbuild/rules_foreign_cc pull request #762
Opened 2021-08-16 17:04 UTC by jheaff1

This PR adds the build of log4cxx to the CI tests.

This should serve as a regression test for the issue described in #344

2021-08-16 18:33 UTC, jheaff1 commented on examples/third_party/log4cxx/compilation.patch
> +--- src/main/cpp/inputstreamreader.cpp	2008-03-31 23:34:09.000000000 +0100
Get rid of this file

2021-08-17 22:23 UTC, UebelAndre requested changes
Thanks!! Two requests so far.

Can you add a `.md` file or something describing the patches? There seems to be quite a few of them and I think it'd be nice to get an overview and maybe some info about when they might not be needed anymore. But it doesn't have to be extensive. 😄 🙏

2021-08-17 22:23 UTC, UebelAndre commented on examples/third_party/log4cxx/BUILD.bazel
> +exports_files(
Can you add the patches to the exports list here?

2021-08-18 09:10 UTC, jheaff1 commented
> Thanks!! Two requests so far.
> 
> Can you add a `.md` file or something describing the patches? There seems to be quite a few of them and I think it'd be nice to get an overview and maybe some info about when they might not be needed anymore. But it doesn't have to be extensive. 😄 🙏

I have managed to reduce the number of patches required by adding a `-Wno-narrowing` compiler flag.

I have added comments to `log4cxx_repositories.bzl` for the patches. Let me know if you would like it reworked further :)

2021-08-18 13:00 UTC, UebelAndre approved these changes
Looks good to me, Thanks for adding this!

2021-08-18 13:00 UTC, merged